# Set prefix to Ctrl + J
unbind C-b
set -g prefix C-j
bind C-j send-prefix

bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

set-option -g mouse on

# Remap x to close panes without confirmation
bind x kill-pane

# panel navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

bind c new-session
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded"
